/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.examendesinf.componente;

import com.mycompany.examandesinf.logica.LogicaNegocio;
import com.mycompany.examendesinf.dto.Personal;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author 34675
 */
public class ListadoPersonalPanel extends javax.swing.JPanel implements Serializable{

    /**
     * Creates new form ListadoPersonalPanel
     */
    private List<Personal> lstPersonal;
    TablePanelPersonalModel modeoTabla;
    public ListadoPersonalPanel() {
        initComponents();
        
    }/**
     *
     */
    public void setCodigoDpto(String codigo){
        txtCodigo.setText(codigo);
    }
    public void configurarPanel(){
        double edadMedia=LogicaNegocio.edadMediaDepartamento(txtCodigo.getText().toUpperCase());
        lblEdadMedia.setText(String.valueOf(edadMedia));
        modeoTabla=new TablePanelPersonalModel(LogicaNegocio.getListaPersonalDepartamento(txtCodigo.getText()));
        tablaPersonal.setModel(modeoTabla);
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonal = new javax.swing.JTable();
        lblEdadMedia = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        refescar = new javax.swing.JButton();

        jLabel1.setText("EDAD MEDIA");

        jScrollPane1.setViewportView(tablaPersonal);

        lblEdadMedia.setText("jLabel2");

        txtCodigo.setPreferredSize(new java.awt.Dimension(50, 22));

        jLabel2.setText("Codigo");

        refescar.setText("Refrescar");
        refescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblEdadMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(refescar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblEdadMedia)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refescar)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refescarActionPerformed
        if(txtCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "El codigo esta vacio", "ERROR CODIGO", JOptionPane.ERROR_MESSAGE);
        }else if(!LogicaNegocio.existeDepartamento(txtCodigo.getText().toUpperCase())){
            JOptionPane.showMessageDialog(this, "El departamento no existe", "ERROR DEPARTAMENTO",JOptionPane.ERROR_MESSAGE);
        }else{
            configurarPanel();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_refescarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEdadMedia;
    private javax.swing.JButton refescar;
    private javax.swing.JTable tablaPersonal;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
