/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package componente.clases.editor;

import componentes.clases.base.ImagenFondo;
import java.io.File;
import java.io.Serializable;
import javax.swing.JFileChooser;

/**
 *
 * @author 34675
 */
public class ImagenFondoJpanel extends javax.swing.JPanel implements Serializable {

    /**
     * Creates new form ImagenFondoJpanel
     */
    public ImagenFondoJpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtruta = new javax.swing.JTextField();
        btnruta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sliderOpacidad = new javax.swing.JSlider();

        jLabel1.setText("Imagen");

        txtruta.setEditable(false);

        btnruta.setText("...");
        btnruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrutaActionPerformed(evt);
            }
        });

        jLabel2.setText("Opacidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(sliderOpacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(txtruta, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnruta)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnruta))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sliderOpacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(210, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrutaActionPerformed
        JFileChooser fileChooser=new JFileChooser();
        int resultado=fileChooser.showOpenDialog(this);
        if (resultado==JFileChooser.APPROVE_OPTION){
            File file=fileChooser.getSelectedFile();
            txtruta.setText(file.getAbsolutePath());
        }

    }//GEN-LAST:event_btnrutaActionPerformed

    /*
    este metodo que duelve un objeto de tipo de las propiedades que se quieren editar
    tiene que estar siempre para ser utilizado por la clase que va a heredar de PropetiesEditorSupport
    y crear nuestro oanel editor junto al componente
    */
    public ImagenFondo getSelectedValue(){
    File f=new File(txtruta.getText());
    float opacidad=sliderOpacidad.getValue()/100f;
    ImagenFondo imagenFondo=new ImagenFondo(f, opacidad);
   return imagenFondo;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnruta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSlider sliderOpacidad;
    private javax.swing.JTextField txtruta;
    // End of variables declaration//GEN-END:variables
}
